export const boards = [
  [
    [
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "", equals: "b" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", times: "b" },
    ],
    [
      { state: "", equals: "t" },
      { state: "sun" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "", times: "t" },
    ],
    [
      { state: "", times: "b" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "sun" },
      { state: "", equals: "b" },
    ],
    [
      { state: "", times: "t" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", equals: "t" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "moon" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "", times: "b" },
    ],
    [
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "", times: "t" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "", equals: "b" },
    ],
    [
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
      { state: "" },
      { state: "", equals: "r" },
      { state: "", equals: "lt" },
    ],
  ],
  [
    [
      { state: "sun" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "moon" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "moon" },
    ],
  ],
  [
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "", equals: "rb" },
      { state: "", equals: "l" },
    ],
    [
      { state: "" },
      { state: "moon" },
      { state: "moon" },
      { state: "" },
      { state: "", equals: "t" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "sun" },
      { state: "" },
    ],
    [
      { state: "", times: "r", equals: "b" },
      { state: "", times: "l" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "", equals: "t" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "sun" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "sun" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "sun" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "moon" },
    ],
  ],
  [
    [
      { state: "" },
      { state: "", equals: "rb" },
      { state: "", equals: "l", times: "b" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", equals: "t", times: "r" },
      { state: "", times: "lt" },
      { state: "" },
      { state: "sun" },
      { state: "moon" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "sun" },
    ],
    [
      { state: "moon" },
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "sun" },
      { state: "moon" },
      { state: "" },
      { state: "", times: "rb" },
      { state: "", times: "lb" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "", times: "tr" },
      { state: "", times: "tl" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "sun" },
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "" },
      { state: "moon" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "", times: "b" },
    ],
    [
      { state: "sun" },
      { state: "moon" },
      { state: "moon" },
      { state: "", equals: "b" },
      { state: "" },
      { state: "", times: "t" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "", equals: "t" },
      { state: "", times: "r" },
      { state: "", times: "l" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "" },
      { state: "", times: "b" },
      { state: "sun" },
      { state: "moon" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "t" },
      { state: "" },
      { state: "" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
    ],
    [
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "sun" },
    ],
    [
      { state: "sun" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "moon" },
    ],
    [
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "" },
      { state: "" },
      { state: "", times: "b" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "sun" },
      { state: "", times: "t" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "moon" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "", times: "rb" },
      { state: "", times: "lr" },
      { state: "", times: "lr" },
      { state: "", times: "lb" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "tb" },
      { state: "sun" },
      { state: "" },
      { state: "", times: "tb" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "tb" },
      { state: "" },
      { state: "" },
      { state: "", times: "tb" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "tr" },
      { state: "", times: "rl" },
      { state: "", times: "rl" },
      { state: "", times: "lt" },
      { state: "sun" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "", equals: "rb" },
      { state: "", equals: "l" },
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "sun" },
    ],
    [
      { state: "", equals: "t" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "", times: "b" },
    ],
    [
      { state: "sun" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "", times: "r" },
      { state: "", times: "lt" },
    ],
  ],
  [
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
    ],
    [
      { state: "" },
      { state: "sun" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "moon" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", equals: "b" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "", times: "b" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", equals: "t" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", times: "t" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "sun" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "sun" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
  ],
  [
    [
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
      { state: "" },
      { state: "moon" },
    ],
    [
      { state: "", equals: "b" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "", equals: "t" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "moon" },
      { state: "" },
      { state: "", equals: "b" },
    ],
    [
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "", equals: "t" },
    ],
    [
      { state: "sun" },
      { state: "" },
      { state: "", times: "r" },
      { state: "", times: "l" },
      { state: "", equals: "r" },
      { state: "", equals: "l" },
    ],
  ],
  [
    [
      { state: "sun" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
    ],
    [
      { state: "" },
      { state: "", times: "rb" },
      { state: "", times: "l", equals: "r" },
      { state: "", times: "r", equals: "l" },
      { state: "", times: "l", equals: "b" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "tb" },
      { state: "", times: "br" },
      { state: "", times: "bl" },
      { state: "", times: "b", equals: "t" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", times: "t", equals: "b" },
      { state: "", times: "tr" },
      { state: "", times: "tl" },
      { state: "", times: "tb" },
      { state: "" },
    ],
    [
      { state: "" },
      { state: "", equals: "tr" },
      { state: "", times: "r", equals: "l" },
      { state: "", times: "lr" },
      { state: "", times: "tl" },
      { state: "" },
    ],
    [
      { state: "moon" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "" },
      { state: "sun" },
    ],
  ],
];

/*
********* EMPTY BOARD *********

  [
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],
    [{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: "" },{ state: ""},],  
  ],

*/
